### ISSUE TITLE
Release upload failed due to 'ContextualVersionConflict: urllib3 1.22'

### ISSUE THREAD

**Issue by leopoldjuergen** [zhmcclient/zhmc-ansible-modules#14]
(venv) vagrant@vagrant-ubuntu-trusty-64:/vagrant$ make upload
==> This will upload zhmc-ansible-modules version 0.2.0 to PyPI!
==> Continue? [yN] y
twine upload build/dist/zhmc_ansible_modules-0.2.0-py2.py3-none-any.whl build/dist/zhmc-ansible-modules-0.2.0.tar.gz
ContextualVersionConflict: urllib3 1.22
make: *** [upload] Error 1

**Comment by andy-maier** [comment]
Fixed in PR #15.
