### ISSUE TITLE
Duplicated get_version() function in setup.py and conf.py

### ISSUE THREAD

**Issue by andy-maier** [zhmcclient/zhmc-ansible-modules#235]
Right now, setup.py and conf.py both contain the same get_version() function, so we are duplicating code.

Here are two approaches for avoiding the code duplication:

- putting it into a module creates the difficulty for setup.py finding it while the package is not yet installed. We don't know how installers invoke setup.py, for example they could set absolute path and import it then the current directory is not in the module search path. So if we go that route, the module would need to be imported into setup.py with explicit import code.
- having the one copy in setup.py and importing setup.py into conf.py does not work because setup.py is not in a package directory. That also could be overcome with explicit import code in conf.py.

**Comment by sabyadi** [comment]
Maybe we can even get rid of setup.py since we are distributing through galaxy.
