### ISSUE TITLE
README link to Galaxy not working

### ISSUE THREAD

**Issue by ijmitch** [zhmcclient/zhmc-ansible-modules#281]
https://galaxy.ansible.com/ibm/zhmc/ gives me 'page not found'.

**Comment by andy-maier** [comment]
Hello. That is true, and the reason for that is that we have not yet released version 1.0.0 which is the first version that will be available from Galaxy.

The last released version is 0.8.3 which is available on Pypi. See the corresponding version of:
* [README](https://github.com/zhmcclient/zhmc-ansible-modules/blob/stable_0.8/README.rst), and
* [documentation](https://zhmc-ansible-modules.readthedocs.io/en/stable/).

**Comment by ijmitch** [comment]
ah, ok - but saying:

> Starting with version 1.0.0, the Ansible modules *are* no longer ...

makes it sound like it's live already.

**Comment by andy-maier** [comment]
Ok, I understand the difficulty now.
That statement in the master branch becomes correct only once 1.0.0 is released, but I think people expect the published README file to correctly describe the current situation. I'll see what we can do about this.
