### ISSUE TITLE
A Partition can not be set in 'absent' state if the Partition is is status 'Terminated'

### ISSUE THREAD

**Issue by leopoldjuergen** [zhmcclient/zhmc-ansible-modules#29]
Ouput:
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "HTTPError: 409,1: The partition is not in a valid state to perform the operation [DELETE /api/partitions/1569c3fe-8c03-11e7-a021-42f2e9ef1641]"}

**Comment by andy-maier** [comment]
Fixed in PR #38.
