### ISSUE TITLE
Things to do for RH IBM Z Certified Collection

### ISSUE THREAD

**Issue by andy-maier** [zhmcclient/zhmc-ansible-modules#369]
TODO: Add items

**Comment by vkathir82** [comment]
1.     **Go to market materials and promotion :**

- Description, Use cases, blogs (announcement blog which we can co-write), video/demos if any
- Customer outreach (e.g. if you want to have a joint session talking to your customer about Ansible) 

2.  **Unified doc** 
Live unified doc work by fixing any conflicting or odd behaviors
- http://collection-doc.moonpie1.fyre.ibm.com/index.html

**Comment by vkathir82** [comment]
1. **Go to market materials and promotion**

- Description, Use cases, blogs (announcement blog which we can co-write), video/demos if any
- Customer outreach (e.g. if you want to have a joint session talking to your customer about Ansible) 

2.  **Unified doc** 
Live unified doc work by fixing any conflicting or odd behaviors
- http://collection-doc.moonpie1.fyre.ibm.com/index.html
