### ISSUE TITLE
Document release to Ansible Automation Hub

### ISSUE THREAD

**Issue by andy-maier** [zhmcclient/zhmc-ansible-modules#454]
The developer documentation (`/docs/source/development.rst`) and possibly the `Makefile` need to be updated to describe the release of the collection to the Ansible Automation Hub.

**Comment by vkathir82** [comment]
From my discussion with Demetrios, the developer documentation is basically very much like Galaxy, we can log in with our access and we upload our collection, it gets scanned and the ansible sanity tests are run.

If they all pass, there is a manual step (has not been automated yet) where we need to send an email to ansible partners to push the upload to hub.

I will setup the meeting to get more details on this.
