### ISSUE TITLE
Request for input: How to model list operations

### ISSUE THREAD

**Issue by andy-maier** [zhmcclient/zhmc-ansible-modules#469]
This issue is used to discuss and seek input for the question how to model list operations for zHMC resources in the Ansible modules.

Since the resource model of the HMC is hierarchical (every resource has a well defined parent resource, and from a parent resource one can list its child resources of a particular type), the approach so far is to look at the parent resource and to include the list direct child resources in the facts of the parent resource. Example: state=facts with the zhmc_cpc module returns the targeted CPC with its properties and also with artificial properties for the list of its adapters, partitions and storage groups (if in DPM mode). In many cases, there are input parameters that control whether a type of child resource is fully expanded to show all of their properties, or just listed. There is currently no specific list operation provided by the zhmc Ansible modules other than this approach.

The disadvantage of the current approach is that if one only needs a list of a particular type of child resources, one has to get the facts for their parent resource as well, plus all the other types of child resources of that parent resource one is not necessarily interested in. This may be a performance and/or size issue, particularly for objects with potentially many types and/or instances of child resources such as CPCs or the Console (not yet supported by the zhmc Collection).

The following is a list of options how to represent list operations for zHMC resources in the Ansible modules, and we'd like to get your input which one you would prefer to add to the current behavior. Also, if you can think of new options, bring them up. Provide your input as comments on this issue.

The idea is to implement the chosen option for all existing and new zhmc Ansible modules.

Options:
* A: Just the current approach of including all child resources in the facts of the parent resource (described above).
* B: Add `state=list` to the Ansible module for the child resource. While technically possible, this would result in an increased complexity: The parent resource would need to be passed in as an additional parameter and that only makes sense for `state=list`, and the structure of the return value now depends on the `state` parameter (i.e. `state=facts` returns a single resource with full properties, while `state=list` returns a list of resources them with a subset of the properties), so there is an additional complexity in the description of the return value.
* C: Add a new Ansible module just for listing the child resources. For example, the new module zhmc_partition_list would list the partitions of a CPC (in DPM mode). It would get the CPC name as the main input parameter and would always return a list of partitions with the subset of properties returned by the "List Partitions of CPC" operation. That avoids the complexities of option B and addresses the performance and size issues of option A.

**Comment by andy-maier** [comment]
So far there is one vote for option C. The OpenStack Ansible modules also model it that way.

**Comment by andy-maier** [comment]
PR #470 implements option C for listing CPCs. It looks good to me, particularly the speed of the operation.

**Comment by vkathir82** [comment]
@andy-maier I vote for Option "C" as it aligns with WS API list operations which is been introduced from the beginning for the zHMC resources for better performances compare to  WS API get properties operations. As a WS API functional tester for more than a decade, I have personally observed advantages of list operations in many use cases.

**Comment by itsBryantP** [comment]
I vote for option C as well. In general, atomic, simple, and precisely scoped modules are more generally preferred as they reduce the complexity and abundance of options/fields for a given module. Its very simple for an Ansible user to extract the resource name from a result and pass that value into a following task to retrieve the child resources.

**Comment by andy-maier** [comment]
Ok, it seems the direction is clear. We'll implement option C. Thanks for the comments!
