### ISSUE TITLE
zhmc_lpar_list module for HMC v2.13.x or lower

### ISSUE THREAD

**Issue by ScYang1991** [zhmcclient/zhmc-ansible-modules#549]
I am currently testing Z HMC collection and found that zhmc_lpar_list module is only available for HMC v2.14 since it uses newly added feature from 2.14 (`GET /api/console/operations/list-permitted-logical-partitions`).

Would it be possible to add new module or option for HMC v2.13.x or lower that allows to list & gather LPAR information?
There are other ways to gather similar information such as using combination of `GET /api/cpcs` , `GET /api/cpcs/{cpc-id}/logical-partitions` and `GET /api/logical-partitions/{logical-partition-id}`.

I could create a python script to list LPARs and related information but it wouldn't be part of the "RedHat Certified Contents".

Thanks.

**Comment by andy-maier** [comment]
Thanks for reporting this. I'll take care of it.

**Comment by andy-maier** [comment]
Hello @ScYang1991 
I just verified that the list_permitted_lpars function works on a 2.14 HMC that manages a z13 CPC.
Would that be sufficient for your use case, or do you really need the support for a 2.13 HMC?

**Comment by andy-maier** [comment]
PR #555 addresses the request for LPAR and partition list.

**Comment by ScYang1991** [comment]
@andy-maier 
Unfortunately, there are only HMC v2.12.1 and v2.13.1 in my environment.
It would be very appreciated if the feature can be added in next version.

**Comment by andy-maier** [comment]
OK, understood. The plan is to include this in version 1.2.0, which should be released in the next couple of weeks.
