### ISSUE TITLE
CPC Activate/Status check after CPC Deactivate error

### ISSUE THREAD

**Issue by HanaOkubo** [zhmcclient/zhmc-ansible-modules#566]
I am currently testing Z HMC collection.
HTTPError occurred during the following operation, what is the cause?
The other modules are successful and do not seem to be network problems.
Also,is it normal that Status cannot be obtained when Deactivating?

・CPC Activate
　＊Error Details
　　fatal: [HMC_test]: FAILED! =>
　　{"changed": false, "msg": "HTTPError: 409,272: Unable to obtain STP configuration data, rc=[0x1000]
　　[GET /api/cpcs/20791c2f-5a7c-3a47-b540-b7689e32c282]"}

・Status check after CPC Deactivate
　＊Error Details
　　ok: [HMC_test] => {
  　　  "script1_res.stdout": {
     　　   "http-status": 409,
  　　      "message": "Unable to obtain STP configuration data, rc=[0x1000]",
    　　    "reason": 272,
    　　    "request-method": "GET",
     　　   "request-uri": "/api/cpcs/264b8713-b023-3de1-bf25-4160b31a6823"
 　　   }
　　}

＊Playbook
    - zhmc_cpc_list:
        hmc_host: "x.x.x"
        hmc_auth:
          userid: "id"
          password: "pass"
          verify: False
      register: result

＊HMC ver
・2.13.1

**Comment by andy-maier** [comment]
@HanaOkubo Sorry for the delay.

If the HMC returns 409, that usually means an access conflict, i.e. someone is updating the resource in parallel with running the runbook. The usual action is to repeat the Ansible playbook after some time. So far, we have not implemented retries upon receiving a 409 status.

Can you please repeat the playbook to see if the error re-occurs?

**Comment by andy-maier** [comment]
Closed since there was no response.
