### ISSUE TITLE
Support load address and parameters for LPAR LOAD

### ISSUE THREAD

**Issue by andy-maier** [zhmcclient/zhmc-ansible-modules#646]
Currently, the zhmc_lpar module supports LPAR LOAD only with a profile.

This ticket is to add support for load address and parameters. The original request for this is in issue #556.

Proposal for adding this support:

For LOAD, the existing support for state=loaded would be extended to specify the following parameters from the "Load Logical Partition" HMC operation: "load-address", "load-parameter", "clear-indicator" and "timeout". The "force" parameter was already an input parameter of the module but needs to be passed on to the Lpar.load() method.

I'm not sure how to handle the "store-status-indicator" parameter of the "Load Logical Partition" HMC operation since it is not clear (to me) how to get that status returned. Unless anyone knows that, I would not implement that parameter in the Ansible module.

**Comment by patwoj** [comment]
Great to hear that you will add support for those LOAD parameters.

Regarding the "store-status-indicator", based on the description from the HMC Operations Guide:

> The store status function stores the current values of the processing unit timer, the clock comparator, the program status word, and the contents of the processor registers in their assigned absolute storage locations.

this "store" operation is performed within CPC, not client side.

Moreover, underlying python-zhmcclient module simply passes this parameter value to HMC:
https://github.com/zhmcclient/python-zhmcclient/blob/master/zhmcclient/_lpar.py#L1225

So there is no need to return and process this parameter. You should pass the "store-status-indicator" to `lpar.load()` function the same way as other boolean parameters.

**Comment by andy-maier** [comment]
I have now added a store_status_indicator input parameter for the module.
See PR #779 which addresses this issue. It is targeted for the upcoming collection version 1.7.0.

**Comment by patwoj** [comment]
I reviewed the code and I see all needed parameters are implemented. Thank you. 
I will test it as soon as you share the new release.
