### ISSUE TITLE
[new feature request] - retrieve zhmc information

### ISSUE THREAD

**Issue by liucgbj** [zhmcclient/zhmc-ansible-modules#650]
currently, there is no module can be used to retrieve zhmc information, e.g. hmc-version, hmc-name, vendor, welcome-text etc.
but following API `GET /api/version` is available in HMC WebService API 2.16.0,  
would you please help to enhance zhmc-ansible-modules and add a new module to do that ?

**Comment by andy-maier** [comment]
Hello @liucgbj , this request has been implemented in PR #684. Note that the PR gets facts about the HMC not only from the "Query API Version" operation, but also from the properties of the Console object.
