### ISSUE TITLE
zhmc_storage_group facts fails when storage group is an NVMe storage group

### ISSUE THREAD

**Issue by ryoung1us** [zhmcclient/zhmc-ansible-modules#864]
**Describe the bug**
The zhmc_storage_group code fails when a NVMe Storage Group is encountered

**Expected behavior**
NVMe storage groups are supported LinuxONE hardware.  We expect them to work with the zhmc_storage_group ansible without causing a failure

**To Reproduce**
Define a NVMe storage group in DPM

tasks:
    - name: "Gather details for CPC {{ my_cpc_name }} "
      zhmc_cpc:
        hmc_host: "{{ ansible_host }}"
        hmc_auth: "{{ hmc_auth[inventory_hostname] }}"
        name: "{{ my_cpc_name }}"
        state: facts
      register: cpcresult
    - debug:
        var: cpcresult 

    - name: "Gather details for storage groups  "
      zhmc_storage_group:
        hmc_host: "{{ ansible_host }}"
        hmc_auth: "{{ hmc_auth[inventory_hostname] }}"
        cpc_name: "{{ my_cpc_name }}"
        name: "{{ item.name }}"
        state: facts
        expand: true
      register: result
      loop: "{{ cpcresult.cpc['storage-groups'] }}"

    - debug:
        var: result

**Environment information**
n/a

* HMC version:
V2.16.0

**Ansible task**
zhmc_storage_group

**Log file**

TASK [Gather details for storage groups] *****************************************************************************************************************

ok: [CTCHPC00HMC1] => (item={'fulfillment-state': 'pending', 'cpc-uri': '/api/cpcs/b0796da1-1b64-3aeb-a31a-c804f9463745', 'name': 'e01p07', 'object-uri': '/api/storage-groups/b64ad41c-abef-11ee-a2e1-00106f26413c', 'type': 'fcp'})

ok: [CTCHPC00HMC1] => (item={'fulfillment-state': 'pending', 'cpc-uri': '/api/cpcs/b0796da1-1b64-3aeb-a31a-c804f9463745', 'name': 'e01p03', 'object-uri': '/api/storage-groups/af451c0e-abef-11ee-b638-00106f26413c', 'type': 'fcp'})

ok: [CTCHPC00HMC1] => (item={'fulfillment-state': 'pending', 'cpc-uri': '/api/cpcs/b0796da1-1b64-3aeb-a31a-c804f9463745', 'name': 'e01p14', 'object-uri': '/api/storage-groups/c2d14aa4-abef-11ee-8fa8-00106f26413c', 'type': 'fcp'})

ok: [CTCHPC00HMC1] => (item={'fulfillment-state': 'pending', 'cpc-uri': '/api/cpcs/b0796da1-1b64-3aeb-a31a-c804f9463745', 'name': 'e01p00', 'object-uri': '/api/storage-groups/aa092460-abef-11ee-bb64-00106f26413c', 'type': 'fcp'})

ok: [CTCHPC00HMC1] => (item={'fulfillment-state': 'pending', 'cpc-uri': '/api/cpcs/b0796da1-1b64-3aeb-a31a-c804f9463745', 'name': 'e01p15', 'object-uri': '/api/storage-groups/c4700f8a-abef-11ee-85fe-00106f26413c', 'type': 'fcp'})

An exception occurred during task execution. To see the full traceback, use -vvv. The error was: KeyError: 'candidate-adapter-port-uris'

failed: [CTCHPC00HMC1] (item={'fulfillment-state': 'complete', 'cpc-uri': '/api/cpcs/b0796da1-1b64-3aeb-a31a-c804f9463745', 'name': 'NVME_test', 'object-uri': '/api/storage-groups/214fc810-9d7e-11ee-abc0-00106f26413c', 'type': 'nvme'}) => {"ansible_loop_var": "item", "changed": false, "item": {"cpc-uri": "/api/cpcs/b0796da1-1b64-3aeb-a31a-c804f9463745", "fulfillment-state": "complete", "name": "NVME_test", "object-uri": "/api/storage-groups/214fc810-9d7e-11ee-abc0-00106f26413c", "type": "nvme"}, "module_stderr": "Traceback (most recent call last):\n  File \"/home/ansibleservice/.ansible/tmp/ansible-tmp-1704748805.9872968-269178-8553555605524/AnsiballZ_zhmc_storage_group.py\", line 107, in <module>\n    _ansiballz_main()\n  File \"/home/ansibleservice/.ansible/tmp/ansible-tmp-1704748805.9872968-269178-8553555605524/AnsiballZ_zhmc_storage_group.py\", line 99, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/ansibleservice/.ansible/tmp/ansible-tmp-1704748805.9872968-269178-8553555605524/AnsiballZ_zhmc_storage_group.py\", line 47, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.ibm.ibm_zhmc.plugins.modules.zhmc_storage_group', init_globals=dict(_module_fqn='ansible_collections.ibm.ibm_zhmc.plugins.modules.zhmc_storage_group', _modlib_path=modlib_path),\n  File \"/usr/lib64/python3.9/runpy.py\", line 225, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib64/python3.9/runpy.py\", line 97, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib64/python3.9/runpy.py\", line 87, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_zhmc_storage_group_payload_ztnkbee2/ansible_zhmc_storage_group_payload.zip/ansible_collections/ibm/ibm_zhmc/plugins/modules/zhmc_storage_group.py\", line 1144, in <module>\n  File \"/tmp/ansible_zhmc_storage_group_payload_ztnkbee2/ansible_zhmc_storage_group_payload.zip/ansible_collections/ibm/ibm_zhmc/plugins/modules/zhmc_storage_group.py\", line 1125, in main\n  File \"/tmp/ansible_zhmc_storage_group_payload_ztnkbee2/ansible_zhmc_storage_group_payload.zip/ansible_collections/ibm/ibm_zhmc/plugins/modules/zhmc_storage_group.py\", line 1078, in perform_task\n  File \"/tmp/ansible_zhmc_storage_group_payload_ztnkbee2/ansible_zhmc_storage_group_payload.zip/ansible_collections/ibm/ibm_zhmc/plugins/modules/zhmc_storage_group.py\", line 1052, in facts\n  File \"/tmp/ansible_zhmc_storage_group_payload_ztnkbee2/ansible_zhmc_storage_group_payload.zip/ansible_collections/ibm/ibm_zhmc/plugins/modules/zhmc_storage_group.py\", line 788, in add_artificial_properties\n  File \"<decorator-gen-137>\", line 2, in list_candidate_adapter_ports\n  File \"/usr/local/lib/python3.9/site-packages/zhmcclient/_logging.py\", line 227, in log_api_call\n    result = func(*args, **kwargs)\n  File \"/usr/local/lib/python3.9/site-packages/zhmcclient/_storage_group.py\", line 703, in list_candidate_adapter_ports\n    port_uris = self.get_property('candidate-adapter-port-uris')\n  File \"<decorator-gen-8>\", line 2, in get_property\n  File \"/usr/local/lib/python3.9/site-packages/zhmcclient/_logging.py\", line 227, in log_api_call\n    result = func(*args, **kwargs)\n  File \"/usr/local/lib/python3.9/site-packages/zhmcclient/_resource.py\", line 386, in get_property\n    return self._properties[name]\nKeyError: 'candidate-adapter-port-uris'\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}

ok: [CTCHPC00HMC1] => (item={'fulfillment-state': 'pending', 'cpc-uri': '/api/cpcs/b0796da1-1b64-3aeb-a31a-c804f9463745', 'name': 'e01p04', 'object-uri': '/api/storage-groups/b107309a-abef-11ee-8f96-00106f26413c', 'type': 'fcp'})

ok: [CTCHPC00HMC1] => (item={'fulfillment-state': 'pending', 'cpc-uri': '/api/cpcs/b0796da1-1b64-3aeb-a31a-c804f9463745', 'name': 'e01p01', 'object-uri': '/api/storage-groups/abd2e59c-abef-11ee-b22b-00106f26413c', 'type': 'fcp'})

**Comment by andy-maier** [comment]
@ryoung1us Thanks for the details. The issue was that the candidate adapter ports only exist for FCP-type storage groups, but the ansible module was calling the corresponding zhmcclient function without checking that first.

I have two PRs up with a fix:
* PR #870 targeting the next functional version 1.8.0
* PR #871 targeting the next fix version 1.7.4

--> Since we don't have end2end testcases for storage groups yet, could you please try the fix by using either one of those PRs?

You can install that by cloning this repo, checking out the branch of the PR, entering the virtual Python environment you normally use, and then running `make install` in the directory of the cloned repo.
